name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm --version
      - run: npm run publish:check
      - name: Publish to npm
        run: npm publish --access public
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: "@yudin-s"
      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_CONFIG_PROVENANCE: "false"
